language: csharp
solution: TopDownHeist.sln
mono: none
dist: xenial
dotnet: 2.2.101
sudo: required

services:
 - docker
script:
 - docker build -t top-down-heist:this TopDownHeist
 - dotnet build
 - dotnet test TopDownHeist.IntegrationTests
